### ISSUE TITLE
监控磁盘空间问题

### ISSUE THREAD

**Issue by wyzhl126** [polardb/polardbx-operator#21]
![图片](https://github.com/polardb/polardbx-operator/assets/27672604/5d4ba5b0-7697-442e-9958-40eb4b2f8b15)
![图片](https://github.com/polardb/polardbx-operator/assets/27672604/d0458ad9-c6f6-4814-a5d1-ebc81ba5cb55)

**Comment by vettalwu** [comment]
Fixed in v1.5.0-beta
