### ISSUE TITLE
polardbx-monitor install failed with helm

### ISSUE THREAD

**Issue by bigdata-user** [polardb/polardbx-operator#22]
Command:           helm install --namespace polardbx-monitor polardbx-monitor polardbx/polardbx-monitor

Result:    Error: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "resource-metrics-server-resources" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "polardbx-monitor"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "polardbx-monitor"

**Comment by vettalwu** [comment]
@bigdata-user  It seems that ClusterRole `resource-metrics-server-resources` is already exists in your k8s cluster. `kubectl get ClusterRole resource-metrics-server-resources` will show this resource info.

Please check if this cluster role is being used. If not, run `kubectl delete  ClusterRole resource-metrics-server-resources` to delete this ClusterRole and re-run helm install.

**Comment by bigdata-user** [comment]
@vettalwu ok! that's right! Thank You
