### ISSUE TITLE
standard instance startup consumes a lot of memory

### ISSUE THREAD

**Issue by clcc2019** [polardb/polardbx-operator#43]
System Info:
  Kernel Version:             4.19.90-2110.8.0.0119.oe1.aarch64
  OS Image:                   openEuler 20.03 (LTS)
  Operating System:           linux
  Architecture:               arm64
  Kubelet Version:            v1.24.16

<img width="986" alt="image" src="https://github.com/polardb/polardbx-operator/assets/46099295/bbb82856-8a9e-4db1-89b7-27fda8f0884d">

**Comment by vettalwu** [comment]
This issue is related to https://github.com/docker-library/mysql/issues/873#issuecomment-1909948195. If your cri is docker, modify `/etc/docker/daemon.json` and add following configs:

```
"default-ulimits": {
    "nofile": {
      "Name": "nofile",
      "Soft": 655350,
      "Hard": 655350
    }
  }
```

Then restart docker daemon.
